# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\api_maps.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(2186, 951)
        self.Enter_lineedit = QtWidgets.QLineEdit(Form)
        self.Enter_lineedit.setGeometry(QtCore.QRect(50, 50, 271, 31))
        self.Enter_lineedit.setObjectName("Enter_lineedit")
        self.search_btn = QtWidgets.QPushButton(Form)
        self.search_btn.setGeometry(QtCore.QRect(320, 50, 31, 31))
        self.search_btn.setObjectName("search_btn")
        self.del_btn = QtWidgets.QPushButton(Form)
        self.del_btn.setGeometry(QtCore.QRect(280, 10, 71, 31))
        self.del_btn.setObjectName("del_btn")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(2030, 40, 91, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.adress_labe = QtWidgets.QLabel(Form)
        self.adress_labe.setGeometry(QtCore.QRect(50, 790, 351, 51))
        self.adress_labe.setObjectName("adress_labe")
        self.index_btn = QtWidgets.QPushButton(Form)
        self.index_btn.setGeometry(QtCore.QRect(50, 730, 41, 41))
        self.index_btn.setObjectName("index_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.search_btn.setText(_translate("Form", "S"))
        self.del_btn.setText(_translate("Form", "del"))
        self.comboBox.setItemText(0, _translate("Form", "Схема"))
        self.comboBox.setItemText(1, _translate("Form", "Гибрид"))
        self.comboBox.setItemText(2, _translate("Form", "Спутник"))
        self.adress_labe.setText(_translate("Form", "АДРЕС АДРЕС АДРЕС АДРЕС АДРЕС АДРЕС"))
        self.index_btn.setText(_translate("Form", "Индекс"))
